# Generated by Django 4.2.6 on 2024-11-11 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_crn', models.ForeignKey(db_column='class_crn', on_delete=django.db.models.deletion.CASCADE, to='attendance.class', to_field='crn')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
            options={
                'db_table': 'attendance_classenrollment',
                'unique_together': {('class_crn', 'student')},
            },
        ),
    ]
